### PR TITLE
plural rules of fallback languages

### LINKED ISSUE #23: Wrong plurals with fallback translations
**Describe the bug**
When the translator falls back to the fallback locale the plural rules of the current locale is used. This is a problem if the rules are different.

**Expected behavior**
The plural rules of the fallback locale is used when the translator falls back to the fallback locale.

### PR DESCRIPTION
**Pull request by maltemattheis**
Use plural rules according to the used language.

Fixes #23

### CODE REVIEW

File: src/lib/translator.ts [hunk 1]
```diff
@@ -53,9 +49,14 @@ export class Translator implements TranslatorInterface {
         //   if none found find by short locale like "de"
         //   if still none found search by the fallback which is by default "en"
         let translated = "";
-        [this.long(), this.short(), this._options.fallback].find(
-            (tag) => !!pattern.find((pat) => !!(translated = this._resources[`${tag}.${pat}`])),
-        );
+        [this.long(), this.short(), this._options.fallback].some((tag) => {
+            const localPattern = [...pattern];
+            if (typeof options.count === "number") {
```
Comment (hbroer) [inline src/lib/translator.ts]: i think this is always string because of line 48

File: src/lib/translator.ts [hunk 2]
```diff
@@ -53,9 +49,14 @@ export class Translator implements TranslatorInterface {
         //   if none found find by short locale like "de"
         //   if still none found search by the fallback which is by default "en"
         let translated = "";
-        [this.long(), this.short(), this._options.fallback].find(
-            (tag) => !!pattern.find((pat) => !!(translated = this._resources[`${tag}.${pat}`])),
-        );
+        [this.long(), this.short(), this._options.fallback].some((tag) => {
```
Comment (hbroer) [inline src/lib/translator.ts]: it may be better to loop first through long() and short() and if then nothing is found to add the pattern + try to find it within the fallback resource.

File: src/lib/translator.ts [hunk 3]
```diff
@@ -24,12 +24,10 @@ export class Translator implements TranslatorInterface {
     private _registry: PluginRegistry = {};
 
     private _locale: Intl.Locale;
-    private _pluralRule: Intl.PluralRules;
```
Comment (hbroer) [inline src/lib/translator.ts:27]: the plural rule is intended to be "cached" to not create a new instance every time. This may be better to add it once for the fallback too instead of create all on the fly

**Review by hbroer — COMMENTED** [review]
it needs some rework

File: src/lib/translator.ts (hunk 1 above)
Comment (maltemattheis) [reply src/lib/translator.ts]: the type of options.count never changes ;)

Comment (hbroer) [reply src/lib/translator.ts]: yes I misread it :D
